### ISSUE TITLE
New device providers returned by the API will cause an error

### ISSUE THREAD

**Issue by razor-x** [seamapi/csharp#33]
This actually affects all eums: https://github.com/search?q=repo%3Aseamapi%2Fcsharp%20StringEnumConverter&type=code

1. Introduce a default value `unknown` for all enums. [This must be the first value, `0`.](https://stackoverflow.com/q/529929/1675295)

```csharp
[EnumMember(Value = "unrecognized")]
Unrecognized = 0,
```

2. Update the enum mapping logic used by `JsonConverter` to map any unknown string to the default value.

**Comment by andrii-balitskyi** [comment]
fixed in https://github.com/seamapi/csharp/pull/34

**Comment by razor-x** [comment]
@andrii-balitskyi I reopened this one because #34 really fixed https://github.com/seamapi/csharp/issues/35

We still have the issue of not handling unknown enums.

**Comment by andrii-balitskyi** [comment]
My bad. I thought it's not relevant anymore since we fixed the generation
